version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - SERVER=DESKTOP-1R6JDGE\SQLEXPRESSION
    #   - PORT=1433
    #   - DATABASE=test
    #   - USERNAME=sa
    #   - PASSWORD=18011871
    ports:
      - 1444:1444
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: sa
        POSTGRES_PASSWORD: 18011871
        POSTGRES_DB: test
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
      ports:
        - 5432:5432
      restart: always

volumes:
  postgres-db-volume:
